from datetime import datetime, timedelta
import helics as h
import json
import logging
import random
from dots_infrastructure.DataClasses import TimeStepInformation, EsdlId, HelicsCalculationInformation
from dots_infrastructure.CalculationServiceHelperFunctions import get_single_param_with_name
from dots_infrastructure.HelicsFederateHelpers import HelicsSimulationExecutor
from esdl import EnergySystem

# Imports generated by the DOTS code generator
from renewable_service_base import RenewableServiceBase
from renewable_service_dataclasses import DayAheadRenewablesOutput, RealTimeRenewablesOutput

LOGGER = logging.getLogger(__name__)

class RenewableService(RenewableServiceBase): 

    def init_calculation_service(self, energy_system: EnergySystem):
        super().init_calculation_service(energy_system)

    def day_ahead_renewables(self, param_dict : dict, simulation_time : datetime, time_step_number : TimeStepInformation, esdl_id : EsdlId, energy_system : EnergySystem):
        # Generate a simple day-ahead forecast with 96 quarter-hour values.
        forecast = []
        base_output_w = random.uniform(200000.0, 600000.0)
        for step in range(96):
            variation = random.uniform(-0.15, 0.15)
            forecast.append(max(0.0, base_output_w * (1.0 + variation)))

        forecast_json = json.dumps({
            "timestamps": [
                (simulation_time + timedelta(minutes=15 * i)).isoformat() for i in range(len(forecast))
            ],
            "generation_w": forecast
        })

        return DayAheadRenewablesOutput(
            planned_generation_da=forecast_json
        )

    def real_time_renewables(self, param_dict : dict, simulation_time : datetime, time_step_number : TimeStepInformation, esdl_id : EsdlId, energy_system : EnergySystem):
        current_max_limit_w = get_single_param_with_name(param_dict, "current_max_power_limit")
        if current_max_limit_w is None:
            current_max_limit_w = 0.0

        potential_available_generation_w = max(0.0, random.uniform(300000.0, 800000.0))
        supplied_power_w = min(potential_available_generation_w, current_max_limit_w * random.uniform(0.8, 1.0))

        return RealTimeRenewablesOutput(
            potential_available_generation_id=potential_available_generation_w,
            supplied_power_id=supplied_power_w
        )

if __name__ == "__main__":

    helics_simulation_executor = RenewableService()
    try:
        LOGGER.info("Starting simulation...")
        helics_simulation_executor.start_simulation()
    except Exception as e:
        LOGGER.error(f"Simulation crashed due to an error: {e}")
        # Raising the error is optional, but good for debugging so it doesn't fail silently
        raise 
    finally:
        LOGGER.info("Ensuring HELICS federate is finalized and simulation is stopped.")
        # This block executes NO MATTER WHAT, guaranteeing the broker is freed.
        helics_simulation_executor.stop_simulation()