from datetime import datetime, timedelta, timezone
import os
import math
import logging
import random
import json
import bisect

from esdl import EnergySystem
import helics as h
from dots_infrastructure.DataClasses import TimeStepInformation, EsdlId
from dots_infrastructure.CalculationServiceHelperFunctions import get_single_param_with_name
from influxdb import InfluxDBClient

# Imports generated by the DOTS code generator
from renewable_service_base import RenewableServiceBase
from renewable_service_dataclasses import DayAheadRenewablesOutput, RealTimeRenewablesOutput

LOGGER = logging.getLogger(__name__)

class RenewableService(RenewableServiceBase): 

    def init_calculation_service(self, energy_system: EnergySystem):
        super().init_calculation_service(energy_system)
        LOGGER.info("Initializing Renewable Service (Realistic v2)...")

        # InfluxDB
        self.influx_host = os.environ.get('INFLUXDB_HOST', 'influxdb')
        self.influx_port = int(os.environ.get('INFLUXDB_PORT', 8086))
        self.read_database = os.environ.get('INFLUXDB_NAME', 'GO-e')
        self.measurement_name = "historical_solar_irradiance"
        
        self.influx_client = InfluxDBClient(
            host=self.influx_host, port=self.influx_port, 
            username=os.environ.get('INFLUXDB_USER', 'admin'), 
            password=os.environ.get('INFLUXDB_PASSWORD', 'admin'), 
            database=self.read_database
        )

        self.pv_properties = {}
        self.prefetched_irradiance = {}
        
        for esdl_id in self.simulator_configuration.esdl_ids:
            # Defaults matching our scenario
            capacity_w = 1_000_000.0
            surface_area = 5000.0
            panel_eff = 0.20
            inv_eff = 0.98
            
            esdl_pv = self.esdl_obj_mapping.get(esdl_id)
            if esdl_pv:
                if getattr(esdl_pv, 'power', 0.0) > 0:
                    capacity_w = float(esdl_pv.power)
                if getattr(esdl_pv, 'surfaceArea', 0.0) > 0:
                    surface_area = float(esdl_pv.surfaceArea)
                if getattr(esdl_pv, 'panelEfficiency', 0.0) > 0:
                    panel_eff = float(esdl_pv.panelEfficiency)
                if getattr(esdl_pv, 'inverterEfficiency', 0.0) > 0:
                    inv_eff = float(esdl_pv.inverterEfficiency)
            
            self.pv_properties[esdl_id] = {
                "capacity_w": capacity_w,
                "surface_area": surface_area,
                "panel_eff": panel_eff,
                "inverter_eff": inv_eff
            }
            self.prefetched_irradiance[esdl_id] = {'timestamps': [], 'values': []}
            LOGGER.info(f"[ESDL] PV {esdl_id}: {capacity_w/1e3:.0f}kW, {surface_area}m2")

        self._prefetch_irradiance()
        
    def _prefetch_irradiance(self):
        try:
            start = self.simulator_configuration.start_time
            if start.tzinfo is None: start = start.replace(tzinfo=timezone.utc)
            stop = start + timedelta(seconds=self.simulator_configuration.simulation_duration_in_seconds + 86400)
            
            query = f'SELECT "Irradiance_W_m2", "esdl_id" FROM "{self.measurement_name}" WHERE time >= \'{start.isoformat()}\' AND time <= \'{stop.isoformat()}\''
            result = self.influx_client.query(query)
            for point in result.get_points():
                eid = point.get('esdl_id')
                if eid in self.prefetched_irradiance:
                    dt = datetime.fromisoformat(point.get('time').replace('Z', '+00:00'))
                    self.prefetched_irradiance[eid]['timestamps'].append(dt)
                    self.prefetched_irradiance[eid]['values'].append(point.get('Irradiance_W_m2'))
        except Exception as e:
            LOGGER.warning(f"Solar InfluxDB pre-fetch skipped: {e}")

    def _get_irradiance(self, esdl_id, t):
        if t.tzinfo is None: t = t.replace(tzinfo=timezone.utc)
        data = self.prefetched_irradiance.get(esdl_id)
        if data and data['timestamps']:
            idx = bisect.bisect_right(data['timestamps'], t) - 1
            if idx >= 0: return data['values'][idx]
        
        # Physics fallback: clear-sky sine model
        hour = t.hour + t.minute / 60.0
        if 6.0 <= hour <= 18.0:
            return max(0.0, 1000.0 * math.sin(math.pi * (hour - 6.0) / 12.0))
        return 0.0

    def calculate_production_w(self, esdl_id, irradiance):
        props = self.pv_properties[esdl_id]
        raw_w = irradiance * props["surface_area"] * props["panel_eff"] * props["inverter_eff"]
        # Cap at nameplate capacity
        capped_w = min(raw_w, props["capacity_w"])
        # Atmospheric variance
        return max(0.0, capped_w * random.uniform(0.98, 1.02))

    def day_ahead_renewables(self, param_dict, simulation_time, time_step_number, esdl_id, energy_system):
        forecast = []
        for i in range(96):
            t = simulation_time + timedelta(minutes=15 * i)
            irrad = self._get_irradiance(esdl_id, t)
            forecast.append(self.calculate_production_w(esdl_id, irrad))

        payload = json.dumps({
            "timestamps": [(simulation_time + timedelta(minutes=15*i)).isoformat() for i in range(96)],
            "generation_w": forecast
        })

        self.influx_connector.set_time_step_data_point(esdl_id, "planned_generation_DA", simulation_time, payload)

        return DayAheadRenewablesOutput(planned_generation_DA=payload)

    def real_time_renewables(self, param_dict, simulation_time, time_step_number, esdl_id, energy_system):
        # We don't block on this input
        limit_w = float('inf')
        for k, v in param_dict.items():
            if "current_max_power_limit" in k:
                limit_w = float(v); break

        irrad = self._get_irradiance(esdl_id, simulation_time)
        potential_w = self.calculate_production_w(esdl_id, irrad)
        supplied_w = min(potential_w, limit_w)

        self.influx_connector.set_time_step_data_point(esdl_id, "Irradiance_W_m2", simulation_time, irrad)
        self.influx_connector.set_time_step_data_point(esdl_id, "Potential_Generation_W", simulation_time, potential_w)
        self.influx_connector.set_time_step_data_point(esdl_id, "Supplied_Power_W", simulation_time, supplied_w)

        return RealTimeRenewablesOutput(
            potential_available_generation_ID=potential_w,
            supplied_power_ID=supplied_w
        )

    def __del__(self):
        if hasattr(self, 'influx_client'):
            try: self.influx_client.close()
            except: pass

if __name__ == "__main__":
    executor = RenewableService()
    try:
        executor.start_simulation()
    except Exception as e:
        LOGGER.error(f"Fatal: {e}")
        raise 
    finally:
        executor.stop_simulation()
