from datetime import datetime
import helics as h
from dots_infrastructure.DataClasses import TimeStepInformation, EsdlId, HelicsCalculationInformation, PublicationDescription, SubscriptionDescription
from dots_infrastructure.HelicsFederateHelpers import HelicsSimulationExecutor
from esdl import EnergySystem, PVInstallation
from dots_infrastructure.EsdlHelperFunctions import EsdlHelperFunctions

# This file is generated from input.json — DO NOT edit this file!

class RenewableServiceBase(HelicsSimulationExecutor):

    def __init__(self):
        super().__init__()
        self.esdl_obj_mapping : dict[EsdlId, PVInstallation]= {}

        
        # Calculation: day_ahead_renewables
        self.day_ahead_renewables_period_seconds = 86400
        day_ahead_renewables_inputs = [
        
        ]
        day_ahead_renewables_outputs = [
        
            PublicationDescription(global_flag=True, 
                                    esdl_type="PVInstallation",
                                    output_name="planned_generation_DA",
                                    output_unit="VECTOR", 
                                    data_type=h.HelicsDataType.VECTOR),
        ]
        day_ahead_renewables_information = HelicsCalculationInformation(
            time_period_in_seconds=86400,
            offset=1, 
            uninterruptible=False, 
            wait_for_current_time_update=False, 
            terminate_on_error=True, 
            calculation_name="day_ahead_renewables", 
            inputs=day_ahead_renewables_inputs, 
            outputs=day_ahead_renewables_outputs, 
            calculation_function=self.day_ahead_renewables
        )
        self.add_calculation(day_ahead_renewables_information)
        # Calculation: renewable_state
        self.renewable_state_period_seconds = 900
        renewable_state_inputs = []
        renewable_state_outputs = [
            PublicationDescription(global_flag=True, 
                                    esdl_type="PVInstallation",
                                    output_name="potential_available_generation_ID",
                                    output_unit="W", 
                                    data_type=h.HelicsDataType.DOUBLE),
            PublicationDescription(global_flag=True, 
                                    esdl_type="PVInstallation",
                                    output_name="supplied_power_ID",
                                    output_unit="W", 
                                    data_type=h.HelicsDataType.DOUBLE),
        ]
        renewable_state_information = HelicsCalculationInformation(
            time_period_in_seconds=900,
            offset=0, 
            uninterruptible=False, 
            wait_for_current_time_update=False, 
            terminate_on_error=True, 
            calculation_name="renewable_state", 
            inputs=renewable_state_inputs, 
            outputs=renewable_state_outputs, 
            calculation_function=self.renewable_state
        )
        self.add_calculation(renewable_state_information)

        # Calculation: renewable_dispatch
        self.renewable_dispatch_period_seconds = 900
        renewable_dispatch_inputs = [
            SubscriptionDescription(esdl_type="ElectricityNetwork", input_name="current_max_power_limit", input_unit="W", input_type=h.HelicsDataType.DOUBLE),
        ]
        renewable_dispatch_outputs = []
        renewable_dispatch_information = HelicsCalculationInformation(
            time_period_in_seconds=900,
            offset=20, 
            uninterruptible=False, 
            wait_for_current_time_update=False, 
            terminate_on_error=True, 
            calculation_name="renewable_dispatch", 
            inputs=renewable_dispatch_inputs, 
            outputs=renewable_dispatch_outputs, 
            calculation_function=self.renewable_dispatch
        )
        self.add_calculation(renewable_dispatch_information)

    def init_calculation_service(self, energy_system: EnergySystem):
        all_esdl_objs = EsdlHelperFunctions.get_all_esdl_objects_from_type(energy_system.eAllContents(), PVInstallation)
        for esdl_obj in all_esdl_objs:
            if hasattr(esdl_obj, "id"):
                self.esdl_obj_mapping[esdl_obj.id] = esdl_obj

    
    def day_ahead_renewables(self, param_dict : dict, simulation_time : datetime, time_step_number : TimeStepInformation, esdl_id : EsdlId, energy_system : EnergySystem):
        pass
    
    def renewable_state(self, param_dict : dict, simulation_time : datetime, time_step_number : TimeStepInformation, esdl_id : EsdlId, energy_system : EnergySystem):
        pass

    def renewable_dispatch(self, param_dict : dict, simulation_time : datetime, time_step_number : TimeStepInformation, esdl_id : EsdlId, energy_system : EnergySystem):
        pass