from datetime import datetime, timedelta, timezone
import os
import math
import logging
import random
import json
import bisect

from esdl import EnergySystem
import helics as h
from dots_infrastructure.DataClasses import TimeStepInformation, EsdlId
from dots_infrastructure.CalculationServiceHelperFunctions import get_single_param_with_name
from influxdb import InfluxDBClient

# Imports generated by the DOTS code generator
from renewable_service_base import RenewableServiceBase
from renewable_service_dataclasses import DayAheadRenewablesOutput, RealTimeRenewablesOutput

LOGGER = logging.getLogger(__name__)

def _extract_influxdb_profile(asset):
    if not hasattr(asset, 'port'): return None
    for p in asset.port:
        if hasattr(p, 'profile'):
            for prof in p.profile:
                if prof.eClass.name == 'InfluxDBProfile':
                    return prof
    return None

def _parse_filters(filters_str):
    if not filters_str: return []
    parsed = []
    pairs = [p.strip() for p in filters_str.split(' AND ')]
    for pair in pairs:
        if '=' in pair:
            k, v = pair.split('=', 1)
            parsed.append({"tag": k.strip(), "value": v.strip().strip("'").strip('"')})
    return parsed

class RenewableService(RenewableServiceBase): 

    def init_calculation_service(self, energy_system: EnergySystem):
        super().init_calculation_service(energy_system)
        LOGGER.info("Initializing Renewable Service (Realistic v2)...")

        self.pv_properties = {}
        self.prefetched_irradiance = {}
        
        for esdl_id in self.simulator_configuration.esdl_ids:
            # Defaults matching our scenario
            capacity_w = 1_000_000.0
            surface_area = 5000.0
            panel_eff = 0.20
            inv_eff = 0.98
            asset_name = "Unknown PV"
            
            esdl_pv = self.esdl_obj_mapping.get(esdl_id)
            if esdl_pv:
                if getattr(esdl_pv, 'power', 0.0) > 0:
                    capacity_w = float(esdl_pv.power)
                if getattr(esdl_pv, 'surfaceArea', 0.0) > 0:
                    surface_area = float(esdl_pv.surfaceArea)
                if getattr(esdl_pv, 'panelEfficiency', 0.0) > 0:
                    panel_eff = float(esdl_pv.panelEfficiency)
                if getattr(esdl_pv, 'inverterEfficiency', 0.0) > 0:
                    inv_eff = float(esdl_pv.inverterEfficiency)
                if getattr(esdl_pv, 'name', None):
                    asset_name = esdl_pv.name
            
            profile = _extract_influxdb_profile(esdl_pv) if esdl_pv else None
            if profile:
                influx_host = os.environ.get('INFLUXDB_HOST') or profile.host or 'influxdb'
                influx_port = int(os.environ.get('INFLUXDB_PORT') or profile.port or 8086)
                influx_db   = os.environ.get('INFLUXDB_NAME') or profile.database or 'GO-e'
                measurement = profile.measurement
                field       = profile.field
                multiplier  = float(profile.multiplier) if profile.multiplier is not None else 1.0
                filters     = _parse_filters(profile.filters)
                LOGGER.info(
                    f"[ESDL Profile] '{asset_name}': host={influx_host}:{influx_port} "
                    f"db={influx_db} measurement={measurement} field={field} "
                    f"filters={filters} multiplier={multiplier}"
                )
            else:
                influx_host = os.environ.get('INFLUXDB_HOST', 'influxdb')
                influx_port = int(os.environ.get('INFLUXDB_PORT', 8086))
                influx_db   = os.environ.get('INFLUXDB_NAME', 'GO-e')
                measurement = 'historical_solar_irradiance'
                field       = 'Irradiance_W_m2'
                multiplier  = 1.0
                filters     = [{"tag": "name", "value": asset_name}]
                LOGGER.warning(f"[ESDL Profile] No InfluxDBProfile found for '{asset_name}' — using defaults.")

            self.pv_properties[esdl_id] = {
                "capacity_w": capacity_w,
                "surface_area": surface_area,
                "panel_eff": panel_eff,
                "inverter_eff": inv_eff,
                "name": asset_name,
                "influx_host": influx_host,
                "influx_port": influx_port,
                "influx_db": influx_db,
                "measurement": measurement,
                "field": field,
                "multiplier": multiplier,
                "filters": filters
            }
            self.prefetched_irradiance[esdl_id] = {'timestamps': [], 'values': []}
            LOGGER.info(f"[ESDL] PV {esdl_id} ('{asset_name}'): {capacity_w/1e3:.0f}kW, {surface_area}m2")

        self._prefetch_irradiance()
        
    def _prefetch_irradiance(self):
        start = self.simulator_configuration.start_time
        if start.tzinfo is None: start = start.replace(tzinfo=timezone.utc)
        stop = start + timedelta(seconds=self.simulator_configuration.simulation_duration_in_seconds + 86400)
        start_str = start.strftime('%Y-%m-%dT%H:%M:%SZ')
        stop_str  = stop.strftime('%Y-%m-%dT%H:%M:%SZ')

        clients = {}
        for esdl_id, props in self.pv_properties.items():
            conn_key = (props['influx_host'], props['influx_port'], props['influx_db'])
            if conn_key not in clients:
                try:
                    clients[conn_key] = InfluxDBClient(
                        host=props['influx_host'], port=props['influx_port'],
                        username=os.environ.get('INFLUXDB_USER', 'admin'),
                        password=os.environ.get('INFLUXDB_PASSWORD', 'admin'),
                        database=props['influx_db']
                    )
                except Exception as e:
                    LOGGER.warning(f"Could not create InfluxDB client for {conn_key}: {e}")
                    continue
            
            client = clients[conn_key]
            measurement = props['measurement']
            field = props['field']
            multiplier = props['multiplier']
            filters = props['filters']

            where_parts = [f"time >= '{start_str}'", f"time <= '{stop_str}'"]
            for f in filters:
                where_parts.append(f"\"{f['tag']}\"='{f['value']}'")
            where_clause = " AND ".join(where_parts)

            query = f'SELECT "{field}" FROM "{measurement}" WHERE {where_clause}'
            try:
                result = client.query(query)
                points_found = 0
                for point in result.get_points():
                    raw_val = point.get(field)
                    if raw_val is None: continue
                    dt = datetime.fromisoformat(point['time'].replace('Z', '+00:00'))
                    self.prefetched_irradiance[esdl_id]['timestamps'].append(dt)
                    self.prefetched_irradiance[esdl_id]['values'].append(float(raw_val) * multiplier)
                    points_found += 1
                LOGGER.info(f"Pre-fetched {points_found} irradiance points for {esdl_id}.")
            except Exception as e:
                LOGGER.warning(f"Solar InfluxDB pre-fetch failed for {esdl_id}: {e}")

    def _get_irradiance(self, esdl_id, t):
        if t.tzinfo is None: t = t.replace(tzinfo=timezone.utc)
        data = self.prefetched_irradiance.get(esdl_id)
        if data and data['timestamps']:
            idx = bisect.bisect_right(data['timestamps'], t) - 1
            if idx >= 0: return data['values'][idx]
        
        # Physics fallback: clear-sky sine model
        hour = t.hour + t.minute / 60.0
        if 6.0 <= hour <= 18.0:
            return max(0.0, 1000.0 * math.sin(math.pi * (hour - 6.0) / 12.0))
        return 0.0

    def calculate_production_w(self, esdl_id, irradiance):
        props = self.pv_properties[esdl_id]
        raw_w = irradiance * props["surface_area"] * props["panel_eff"] * props["inverter_eff"]
        # Cap at nameplate capacity
        capped_w = min(raw_w, props["capacity_w"])
        # Atmospheric variance
        return max(0.0, capped_w * random.uniform(0.98, 1.02))

    def day_ahead_renewables(self, param_dict, simulation_time, time_step_number, esdl_id, energy_system):
        forecast = []
        for i in range(96):
            t = simulation_time + timedelta(minutes=15 * i)
            irrad = self._get_irradiance(esdl_id, t)
            forecast.append(self.calculate_production_w(esdl_id, irrad))

        payload = json.dumps({
            "timestamps": [(simulation_time + timedelta(minutes=15*i)).isoformat() for i in range(96)],
            "generation_w": forecast
        })

        self.influx_connector.set_time_step_data_point(esdl_id, "planned_generation_DA", simulation_time, payload)

        return DayAheadRenewablesOutput(planned_generation_DA=payload)

    def real_time_renewables(self, param_dict, simulation_time, time_step_number, esdl_id, energy_system):
        # We don't block on this input
        limit_w = float('inf')
        for k, v in param_dict.items():
            if "current_max_power_limit" in k:
                limit_w = float(v); break

        irrad = self._get_irradiance(esdl_id, simulation_time)
        potential_w = self.calculate_production_w(esdl_id, irrad)
        supplied_w = min(potential_w, limit_w)

        self.influx_connector.set_time_step_data_point(esdl_id, "Irradiance_W_m2", simulation_time, irrad)
        self.influx_connector.set_time_step_data_point(esdl_id, "Potential_Generation_W", simulation_time, potential_w)
        self.influx_connector.set_time_step_data_point(esdl_id, "Supplied_Power_W", simulation_time, supplied_w)

        return RealTimeRenewablesOutput(
            potential_available_generation_ID=potential_w,
            supplied_power_ID=supplied_w
        )

    def __del__(self):
        pass

if __name__ == "__main__":
    executor = RenewableService()
    try:
        executor.start_simulation()
    except Exception as e:
        LOGGER.error(f"Fatal: {e}")
        raise 
    finally:
        executor.stop_simulation()
