from datetime import datetime
import helics as h
from dots_infrastructure.DataClasses import TimeStepInformation, EsdlId, HelicsCalculationInformation, PublicationDescription, SubscriptionDescription
from dots_infrastructure.HelicsFederateHelpers import HelicsSimulationExecutor
from esdl import EnergySystem, PVInstallation
from dots_infrastructure.EsdlHelperFunctions import EsdlHelperFunctions

# This file is generated, DO NOT edit this file!

class RenewableServiceBase(HelicsSimulationExecutor):

    def __init__(self):
        super().__init__()
        self.esdl_obj_mapping : dict[EsdlId, PVInstallation]= {}

        
        # Calculation: day_ahead_renewables
        self.day_ahead_renewables_period_seconds = 86400
        day_ahead_renewables_inputs = [
        
        ]
        day_ahead_renewables_outputs = [
        
            PublicationDescription(global_flag=True, 
                                    esdl_type="PVInstallation",
                                    output_name="planned_generation_DA",
                                    output_unit="JSON", 
                                    data_type=h.HelicsDataType.STRING),
        ]
        day_ahead_renewables_information = HelicsCalculationInformation(
            time_period_in_seconds=86400,
            offset=0, 
            uninterruptible=False, 
            wait_for_current_time_update=False, 
            terminate_on_error=True, 
            calculation_name="day_ahead_renewables", 
            inputs=day_ahead_renewables_inputs, 
            outputs=day_ahead_renewables_outputs, 
            calculation_function=self.day_ahead_renewables
        )
        self.add_calculation(day_ahead_renewables_information)
        # Calculation: real_time_renewables
        self.real_time_renewables_period_seconds = 900
        real_time_renewables_inputs = [
        
        ]
        real_time_renewables_outputs = [
        
            PublicationDescription(global_flag=True, 
                                    esdl_type="PVInstallation",
                                    output_name="potential_available_generation_ID",
                                    output_unit="W", 
                                    data_type=h.HelicsDataType.DOUBLE),
            PublicationDescription(global_flag=True, 
                                    esdl_type="PVInstallation",
                                    output_name="supplied_power_ID",
                                    output_unit="W", 
                                    data_type=h.HelicsDataType.DOUBLE),
        ]
        real_time_renewables_information = HelicsCalculationInformation(
            time_period_in_seconds=900,
            offset=0, 
            uninterruptible=False, 
            wait_for_current_time_update=False, 
            terminate_on_error=True, 
            calculation_name="real_time_renewables", 
            inputs=real_time_renewables_inputs, 
            outputs=real_time_renewables_outputs, 
            calculation_function=self.real_time_renewables
        )
        self.add_calculation(real_time_renewables_information)

    def init_calculation_service(self, energy_system: EnergySystem):
        all_esdl_objs = EsdlHelperFunctions.get_all_esdl_objects_from_type(energy_system.eAllContents(), PVInstallation)
        for esdl_obj in all_esdl_objs:
            if hasattr(esdl_obj, "id"):
                self.esdl_obj_mapping[esdl_obj.id] = esdl_obj

    
    def day_ahead_renewables(self, param_dict : dict, simulation_time : datetime, time_step_number : TimeStepInformation, esdl_id : EsdlId, energy_system : EnergySystem):
        pass
    
    def real_time_renewables(self, param_dict : dict, simulation_time : datetime, time_step_number : TimeStepInformation, esdl_id : EsdlId, energy_system : EnergySystem):
        pass
    